SELECT 
	DISTINCT UPPER(V.PROGRAM)
FROM 
	V$SESSION V 
WHERE 
	UPPER(V.USERNAME) = 'USERNAME'
	AND (UPPER(V.TERMINAL) LIKE '%HOSTNAME'OR UPPER(V.MACHINE) LIKE '%HOSTNAME')
	AND UPPER(USERNAME) NOT IN ('SAC_CIS','SAC_SUPORTE','JUMANJI','CIS_BH','ZANK')
