SELECT
	TRIM(U.SQL_FULLTEXT)
FROM
	V$SESSION V, V$SQL U
WHERE
	UPPER(V.USERNAME) = 'USERNAME'
	AND V.SQL_ID = U.sql_id
	AND UPPER(V.PROGRAM) = 'NOMEPROCESSO.EXE'
	AND UPPER(V.STATUS) = 'ACTIVE'
	AND (UPPER(V.TERMINAL) LIKE '%HOSTNAME' OR UPPER(V.MACHINE) LIKE '%HOSTNAME')
	AND UPPER(V.OSUSER) LIKE '%USUARIOOS'
	AND UPPER(USERNAME) NOT IN ('SAC_CIS','SAC_SUPORTE','JUMANJI','CIS_BH','ZANK')
ORDER BY
	U.LAST_ACTIVE_TIME
