SELECT 
	DISTINCT SUBSTR(S.OSUSER, (INSTR(S.OSUSER, '\', -1) + 1)) AS OS_USER
FROM
	V$SESSION S
WHERE
	S.USERNAME LIKE 'USUARIO'
	AND (UPPER(S.MACHINE) LIKE '%HOSTNAME' OR UPPER(S.TERMINAL) LIKE '%HOSTNAME')
